version: '3.1'

services:
  mongo:
    image: mongo:6.0.13
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: classifai
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "localhost:27017:27017"
    
volumes:
  mongo-data:
    driver: local


mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"