name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REQUIREMENTS: requirements.txt